version: 0.1
phase:
    install:
        commands:
            - npm install time
            - aws cloudformation package --template-file samTeplate.yaml --s3-bucket sample-serverless-pipeline --output-template-file NewSamTemplate.yaml
artifacts:
    type: zip
    files:
        - NewSampleTemplate.yaml
